"""Added language enum and column

Revision ID: 50cf97f5269d
Revises: 829aba2a9e0a
Create Date: 2025-08-30 06:09:40.591938

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "50cf97f5269d"
down_revision: Union[str, None] = "829aba2a9e0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "submissions",
        sa.Column(
            "language",
            sa.Enum("PYTHON", "JAVASCRIPT", "JAVA", name="language"),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_submissions_language"), "submissions", ["language"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_submissions_language"), table_name="submissions")
    op.drop_column("submissions", "language")
    # ### end Alembic commands ###
