from typing import Protocol, Any, Optional, Dict, Sequence
from uuid import UUID
from app.models.postgre import Submission, Language


class SubmissionsPGRepo(Protocol):
    async def find_by_uuid(self, uuid: UUID) -> Optional["Submission"]: ...
    async def find_all(self) -> Sequence["Submission"]: ...
    async def find_by_hash(self, code_hash: str) -> Optional["Submission"]: ...
    async def create(
        self, *, title: str, language: Language, mongo_id: str, code_hash: str
    ) -> "Submission": ...


class SubmissionsMongoRepo(Protocol):
    async def find(self, mongo_id: str) -> Optional[Dict[str, Any]]: ...
    async def find_all(self) -> Optional[Dict[str, Any]]: ...
    async def insert(self, user_input: Dict[str, Any], ai_text: str | None) -> str: ...
