from typing import Protocol, Any, Dict, Optional
from uuid import UUID

class SubmissionsPGRepo(Protocol):
    async def get_by_uuid(self, uuid: UUID) -> Optional["Submission"]: ...
    async def create(self, *, title: str, status: str, language: str, mongo_id: str) -> "Submission": ...

class SubmissionsMongoRepo(Protocol):
    async def get(self, mongo_id: str) -> Optional[Dict[str, Any]]: ...
    async def insert(self, doc: Dict[str, Any]) -> str: ...
