from typing import Protocol, Any, Optional, Sequence, List
from uuid import UUID
from app.models.postgre import Submission, Language
from app.models.mongo import SubmissionDocument


class SubmissionsPGRepo(Protocol):
    async def find_by_uuid(self, uuid: UUID) -> Optional["Submission"]: ...
    async def find_all(self) -> Sequence["Submission"]: ...
    async def find_by_hash(self, code_hash: str) -> Optional["Submission"]: ...
    async def create(
        self, *, title: str, language: Language, mongo_id: str, code_hash: str
    ) -> "Submission": ...


class SubmissionsMongoRepo(Protocol):
    async def find(self, mongo_id: str) -> Optional[SubmissionDocument]: ...
    async def find_all(self) -> List[SubmissionDocument]: ...
    async def insert(self, user_input: dict[str, Any], ai_text: str | None) -> str: ...
