name: CI

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  lint-type-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install project (optional)
        run: |
          if [ -f pyproject.toml ]; then pip install -e . || true; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install dev tools
        run: |
          python -m pip install --upgrade pip
          pip install "ruff>=0.5" "mypy>=1.10" pytest pytest-cov bandit pip-audit

      - name: Ruff - format check
        run: ruff format --check .
      - name: Ruff - lint
        run: ruff check . --output-format=github
      - name: mypy
        run: mypy --pretty --show-error-codes app